"""'添加User模型类'

Revision ID: 5c445455bd4f
Revises: 
Create Date: 2020-09-29 10:31:00.442390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c445455bd4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nick_name', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('qq', sa.String(length=11), nullable=False),
    sa.Column('move_mobile', sa.String(length=11), nullable=True),
    sa.Column('fixed_mobile', sa.String(length=15), nullable=True),
    sa.Column('gender', sa.Enum('MAN', 'WOMAN'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fixed_mobile'),
    sa.UniqueConstraint('move_mobile'),
    sa.UniqueConstraint('nick_name'),
    sa.UniqueConstraint('qq')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
